import product_room
import room_type
import rate_type
import amenities
import facilities
import rooms
import floors
import section
import night_audit
import packages
import hotel_settings
import cancellation_policy
import booking_policy
import group_booking
import booking_source_category
import booking_source
import reservation
import reservation_line
import stay
import res_partner
import reference
import invoice_status
